// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddSecret(arg1, arg2, arg3) {
  return window['go']['main']['DesktopService']['AddSecret'](arg1, arg2, arg3);
}

export function BrowseRepository() {
  return window['go']['main']['DesktopService']['BrowseRepository']();
}

export function CancelDeviceLogin(arg1) {
  return window['go']['main']['DesktopService']['CancelDeviceLogin'](arg1);
}

export function CreateEnvironment(arg1) {
  return window['go']['main']['DesktopService']['CreateEnvironment'](arg1);
}

export function DeleteEnvironment(arg1) {
  return window['go']['main']['DesktopService']['DeleteEnvironment'](arg1);
}

export function DeleteSecret(arg1, arg2) {
  return window['go']['main']['DesktopService']['DeleteSecret'](arg1, arg2);
}

export function DiffHistory(arg1, arg2, arg3) {
  return window['go']['main']['DesktopService']['DiffHistory'](arg1, arg2, arg3);
}

export function EditSecret(arg1, arg2, arg3) {
  return window['go']['main']['DesktopService']['EditSecret'](arg1, arg2, arg3);
}

export function GetAuthStatus() {
  return window['go']['main']['DesktopService']['GetAuthStatus']();
}

export function GetDeviceLoginStatus(arg1) {
  return window['go']['main']['DesktopService']['GetDeviceLoginStatus'](arg1);
}

export function GetRepoStatus() {
  return window['go']['main']['DesktopService']['GetRepoStatus']();
}

export function Initialize() {
  return window['go']['main']['DesktopService']['Initialize']();
}

export function ListEnvironments() {
  return window['go']['main']['DesktopService']['ListEnvironments']();
}

export function ListHistory(arg1) {
  return window['go']['main']['DesktopService']['ListHistory'](arg1);
}

export function ListSecrets(arg1) {
  return window['go']['main']['DesktopService']['ListSecrets'](arg1);
}

export function Logout() {
  return window['go']['main']['DesktopService']['Logout']();
}

export function PullSecrets(arg1) {
  return window['go']['main']['DesktopService']['PullSecrets'](arg1);
}

export function RenameEnvironment(arg1, arg2) {
  return window['go']['main']['DesktopService']['RenameEnvironment'](arg1, arg2);
}

export function RestoreHistory(arg1, arg2) {
  return window['go']['main']['DesktopService']['RestoreHistory'](arg1, arg2);
}

export function SelectRepository(arg1) {
  return window['go']['main']['DesktopService']['SelectRepository'](arg1);
}

export function StartDeviceLogin() {
  return window['go']['main']['DesktopService']['StartDeviceLogin']();
}

export function SwitchEnvironment(arg1) {
  return window['go']['main']['DesktopService']['SwitchEnvironment'](arg1);
}

export function SyncSecrets(arg1) {
  return window['go']['main']['DesktopService']['SyncSecrets'](arg1);
}
