// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {desktop} from '../models';
import {app} from '../models';

export function AddSecret(arg1:string,arg2:string,arg3:string):Promise<void>;

export function BrowseRepository():Promise<desktop.RepoInfo>;

export function CancelDeviceLogin(arg1:string):Promise<void>;

export function CreateEnvironment(arg1:string):Promise<void>;

export function DeleteEnvironment(arg1:string):Promise<void>;

export function DeleteSecret(arg1:string,arg2:string):Promise<void>;

export function DiffHistory(arg1:string,arg2:number,arg3:number):Promise<app.Diff>;

export function EditSecret(arg1:string,arg2:string,arg3:string):Promise<void>;

export function GetAuthStatus():Promise<desktop.AuthStatus>;

export function GetDeviceLoginStatus(arg1:string):Promise<desktop.DeviceStatus>;

export function GetRepoStatus():Promise<desktop.RepoInfo>;

export function Initialize():Promise<Record<string, any>>;

export function ListEnvironments():Promise<Array<desktop.Environment>>;

export function ListHistory(arg1:string):Promise<Array<desktop.HistoryEntry>>;

export function ListSecrets(arg1:string):Promise<desktop.SecretsResponse>;

export function Logout():Promise<void>;

export function PullSecrets(arg1:string):Promise<void>;

export function RenameEnvironment(arg1:string,arg2:string):Promise<void>;

export function RestoreHistory(arg1:string,arg2:number):Promise<void>;

export function SelectRepository(arg1:string):Promise<desktop.RepoInfo>;

export function StartDeviceLogin():Promise<desktop.DeviceStart>;

export function SwitchEnvironment(arg1:string):Promise<void>;

export function SyncSecrets(arg1:string):Promise<void>;
